name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUST_LOG: lasr=trace
      RUST_BACKTRACE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      run: rustup component add clippy
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
